#!/usr/bin/env bash

# Send a desktop notification displaying the remaining amount of energy stored in `BAT0`
# if (and only if) the battery is currently discharging.  This is what works on my
# ThinkPad X13 Gen 2 and may not be portable to other laptops without changes.  TODO:
# increase the urgency as the battery depletes?

set -o nounset -o pipefail

read -r status < /sys/class/power_supply/BAT0/status || exit
[[ $status != 'Discharging' ]] && exit

btry_output=$(~/dotfiles/home/bin/btry)
percentage_in_parens=${btry_output##* Wh }
(( ${percentage_in_parens:1:-2} > 40 )) && exit

notify-send -c ephemeral - $'<small>Battery status</small>\n'"$btry_output"
