#!/bin/bash

# TODO: consider sourcing the scripts in /etc/X11/xinit/xinitrc.d/ like
# /etc/X11/xinit/xinitrc does.

# Merge X resource files below `~/.xresources/`.
if [[ -d ~/.xresources ]]; then
   for f in ~/.xresources/*; do
      [[ -f $f ]] && xrdb -merge "$f"
   done
fi

[[ -f ~/dotfiles/misc/keymap.xkb ]] && xkbcomp ~/dotfiles/misc/keymap.xkb "$DISPLAY"

xset -b +fp /usr/local/share/fonts

xbindkeys

# Use Control as another Escape key without breaking its normal modifier key
# functionality.
xcape

# Auto-hide the mouse cursor.  See <https://github.com/Airblader/unclutter-xfixes>.
unclutter --jitter 1 --ignore-buttons 4,5,6,7 --start-hidden --fork

# Reduce the autorepeat delay.  The default is 660 (milliseconds).
xset r rate 250

# Start the dunst(1) notification daemon.
dunst &

case $1 in
   # The default is i3: start it when $1 is empty.
   i3 | '') exec i3;;
   xmonad) xsetroot -cursor_name left_ptr
           exec xmonad;;
   # I didn't realize this was possible.  Not very useful for Firefox but [maybe for
   # graphical games](https://wiki.archlinux.org/title/Xinit).
   firefox) exec ${FIREFOX:-firefox-esr};;
   # Try to start whatever $1 is.
   *) exec "$1";;
esac
