"
" $MGYVIMRC
"
" This is also sourced when starting the GUI later with :gui.  That makes it preferable to
" put stuff specific to gVim here (instead of into .vimrc behind has('gui_running') if
" statements).  Neovim doesn't use this file.

" Remove all autocommands for the 'vimrc_gvimrc' group.
augroup vimrc_gvimrc
   autocmd!
augroup END

" Don't automatically yank all visual selections into the "* register.
set guioptions-=a

" Disable GUI tab buttons and remove the menu bar, toolbar, right-hand scrollbar and
" left-hand scrollbar.
set guioptions-=e go-=m go-=T go-=r go-=L

if has('win32')
   set guifont=Consolas:h10,Source_Code_Pro:h9
   silent! colorscheme jellyjam
   " Maximize Vim's window on startup.  See :h win16-maximixed.
   autocmd vimrc_gvimrc GUIEnter * simalt ~x
else
   set guifont=Ubuntu\ Mono\ 7,Source\ Code\ Pro\ Medium\ 6
   silent! colorscheme jellyjam
end
let g:solarized_italic = 0

" Search for 'hi nontext' in vimrc for explanations.
hi nontext guifg=bg gui=NONE

" No bell, no flash.  When the GUI starts, 't_vb' is reset to its default value, so we
" need to set it again here.  See :h visualbell.
set t_vb=

" Don't make the cursor blink!
set guicursor+=a:blinkoff0

" vim: tw=90 sts=-1 sw=3 et
