directory: ~/music
plugins: beatport info edit fetchart embedart
asciify_paths: yes
# See <https://github.com/beetbox/beets/issues/323>.
path_sep_replace: '-'

import:
    timid: yes

# See <https://beets.readthedocs.io/en/latest/reference/config.html#replace>.
replace:
    '[\x00-\x1f]': '-'
    '[\x21-\x2f\x3a-\x40\x5b-\x5e\x60\x7b-\x7e]': '-'
    '\s+$': ''
    '^\s+': ''
    '\s': '_'

# See <https://beets.readthedocs.io/en/latest/reference/config.html#path-format-configuration>.
paths:
    default: %lower{$albumartist/$album%aunique{}/$track-$title}
    singleton: non-album/%lower{$artist/$title}
    comp: compilations/%lower{$album%aunique{}/$track-$title}

embedart:
    # "Avoid embedding album art for files that already have art embedded."  See
    # <https://beets.readthedocs.io/en/latest/plugins/embedart.html>.
    ifempty: yes
    maxwidth: 1000
