#!/usr/bin/env bash

read -r x y < <(xrandr | sed -En 's/.*primary [0-9x]+\+([0-9]+)\+([0-9]+).*/\1 \2/p')

(( x -= 3 ))
(( y -= 3 ))

f=$(mktemp) || exit $?

cleanup() {
   rm "$f"
}
trap cleanup EXIT

cat <<EOF > "$f"
{
   "rect": {
      "height": 789,
      "width": 2566,
      "x": $x,
      "y": $y
   },
   "type": "floating_con",
   "nodes": [
      {
         "floating": "user_on",
         "swallows": [
            {
               "class": "^XTerm$",
               "instance": "^scratchpad$"
            }
         ],
         "type": "con"
      }
   ]
}
EOF

i3-msg "append_layout $f"
