#!/usr/bin/env bash

cd /sys/class/backlight/intel_backlight || exit

brightness=$(<brightness) || exit

[[ $1 == increment ]] && (( brightness < 400 )) && {
   echo $((++brightness)) > brightness || ((--brightness))
}
[[ $1 == decrement ]] && (( brightness > 0 )) && {
   echo $((--brightness)) > brightness || ((++brightness))
}

dunstify -u low -t 2000 -a hzVgHJS3 -r 699814432 - \
   "<small>Screen brightness</small>\n$brightness"
