#!/usr/bin/env bash

workspace_exists=$(i3-msg -t get_workspaces | jq 'any (.name == "dmesg")')
i3-msg 'workspace dmesg'
[[ $workspace_exists == 'true' ]] && exit

i3-msg -q 'append_layout ~/.config/i3/dmesg-workspace.json'

xterm -title dmesg -e 'sudo dmesg --follow --human' &
xterm -title journalctl -e 'journalctl --dmesg --follow -n 17 -o cat' &
