#!/usr/bin/env bash

set -o nounset -o pipefail
shopt -s extglob

if [[ $0 != *reforge ]]; then
   IFS= read -r d < <(
      find ~/wip -maxdepth 1 -type d -name 'forge.??????????' -printf '%A@\t%p\n' |
      sort -rn | cut -f2
   )
fi

if [[ ! -v d || ! -d $d ]]; then
   d=$(mktemp -d ~/wip/forge.XXXXXXXXXX) || exit
   cat > "$d/main.cpp" <<'EOF'
#include <iostream>

using namespace std;

int main() {
   
}
EOF
   cat > "$d/makefile" <<'EOF'
main: main.cpp
	g++ -Wall -Wextra -pedantic $< -o $@
EOF
   vim "$d/main.cpp" +'set aw' +'cd %:h' +6 +'startinsert!' || exit
else
   vim "$d/main.cpp" +'set aw' +'cd %:h' || exit
fi
