#!/usr/bin/env bash

set -o nounset -o pipefail
shopt -s extglob

if [[ $0 != *reforge ]]; then
   IFS= read -r d < <(
      find ~/tmp/forge -mindepth 1 -maxdepth 1 -type d -printf '%A@\t%p\n' |
      sort -rn | cut -f2
   )
fi

if [[ -v d && -d $d ]]; then
   vim "$d/main.cpp" +'set aw' +'cd %:h'
   exit
fi

mkdir -p ~/tmp/forge || exit
until d=~/tmp/forge/$(qualified-noun) && mkdir "$d"; do :; done

cat > "$d/main.cpp" <<'EOF'
#include <iostream>

using namespace std;

int main() {
   
}
EOF

cat > "$d/makefile" <<'EOF'
main: main.cpp
	g++ -Wall -Wextra -pedantic $< -o $@
EOF

vim "$d/main.cpp" +'set aw' +'cd %:h' +6 +'startinsert!'
