#!/usr/bin/env bash

set -o nounset -o pipefail

if [[ ! -f /tmp/man$1.txt ]]; then
   man -kS "$1" . | awk '{ print $1, $2 }' > "/tmp/man$1.txt"
fi

export FZF_DEFAULT_OPTS="--prompt '? ' --color dark,hl:yellow:regular,fg+:white:regular
   --color hl+:yellow:regular:reverse,query:white:regular,info:gray:regular
   --color prompt:yellow:regular,pointer:yellow:bold ${FZF_DEFAULT_OPTS:-}"

# shellcheck disable=SC2016
mapfile -t selection < <(xterm -name 'floating xterm' -geometry 36x24 -e '
   fzf < /proc/$PPID/fd/0 > /proc/$PPID/fd/1' < "/tmp/man$1.txt" |
   sed -r 's/(.*) \((.*)\)/\2\n\1/')

[[ ${selection[0]} && ${selection[1]} ]] || exit

LC_CTYPE=en_US exec xterm -sl 0 -name 'floating man' \
   -title "${selection[1]}(${selection[0]}) manual page" \
   -geometry 88x68 -e man -E latin1 --nj --nh "${selection[@]}"
